# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-04 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='output',
            field=models.TextField(),
        ),
    ]
